// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const clipsTable = {
  name: "clips",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    projectId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "project_id",
    },
    trackId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "track_id",
    },
    sampleId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "sample_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    startSampleFrame: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "start_sample_frame",
    },
    durationSampleFrames: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "duration_sample_frames",
    },
    sourceStartSampleFrame: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "source_start_sample_frame",
    },
    gain: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const projectUsersTable = {
  name: "projectUsers",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    projectId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "project_id",
    },
    userId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "user_id",
    },
    role: {
      type: "string",
      optional: false,
      customType: null as unknown as "owner" | "collaborator",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
  serverName: "project_users",
} as const;
const projectsTable = {
  name: "projects",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    duration: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    sampleRate: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "sample_rate",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const samplesTable = {
  name: "samples",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    projectId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "project_id",
    },
    storageUrl: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "storage_url",
    },
    waveformUrl: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
      serverName: "waveform_url",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    durationSampleFrames: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "duration_sample_frames",
    },
    sampleRate: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "sample_rate",
    },
    channels: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
  },
  primaryKey: ["id"],
} as const;
const trackEffectsTable = {
  name: "trackEffects",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    trackId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "track_id",
    },
    order: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    enabled: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
    effectData: {
      type: "json",
      optional: false,
      customType: null as unknown as {
        type: "filter";
        cutoff: number;
        resonance: number;
        filterType: "lowpass" | "highpass" | "bandpass" | "notch";
      },
      serverName: "effect_data",
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "track_effects",
} as const;
const tracksTable = {
  name: "tracks",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    projectId: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "project_id",
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    order: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
    },
    color: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    muted: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
    solo: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
    },
    gain: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    pan: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
    },
    createdAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: false,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
} as const;
const userTable = {
  name: "user",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    image: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
} as const;
const clipsRelationships = {
  project: [
    { sourceField: ["projectId"], destField: ["id"], destSchema: "projects", cardinality: "one" },
  ],
  track: [
    { sourceField: ["trackId"], destField: ["id"], destSchema: "tracks", cardinality: "one" },
  ],
  sample: [
    { sourceField: ["sampleId"], destField: ["id"], destSchema: "samples", cardinality: "one" },
  ],
} as const;
const projectsRelationships = {
  users: [
    {
      sourceField: ["id"],
      destField: ["projectId"],
      destSchema: "projectUsers",
      cardinality: "many",
    },
  ],
  tracks: [
    { sourceField: ["id"], destField: ["projectId"], destSchema: "tracks", cardinality: "many" },
  ],
  samples: [
    { sourceField: ["id"], destField: ["projectId"], destSchema: "samples", cardinality: "many" },
  ],
  clips: [
    { sourceField: ["id"], destField: ["projectId"], destSchema: "clips", cardinality: "many" },
  ],
} as const;
const projectUsersRelationships = {
  project: [
    { sourceField: ["projectId"], destField: ["id"], destSchema: "projects", cardinality: "one" },
  ],
  user: [{ sourceField: ["userId"], destField: ["id"], destSchema: "user", cardinality: "one" }],
} as const;
const samplesRelationships = {
  project: [
    { sourceField: ["projectId"], destField: ["id"], destSchema: "projects", cardinality: "one" },
  ],
  clips: [
    { sourceField: ["id"], destField: ["sampleId"], destSchema: "clips", cardinality: "many" },
  ],
} as const;
const trackEffectsRelationships = {
  track: [
    { sourceField: ["trackId"], destField: ["id"], destSchema: "tracks", cardinality: "one" },
  ],
} as const;
const tracksRelationships = {
  project: [
    { sourceField: ["projectId"], destField: ["id"], destSchema: "projects", cardinality: "one" },
  ],
  clips: [
    { sourceField: ["id"], destField: ["trackId"], destSchema: "clips", cardinality: "many" },
  ],
  effects: [
    {
      sourceField: ["id"],
      destField: ["trackId"],
      destSchema: "trackEffects",
      cardinality: "many",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    clips: clipsTable,
    projectUsers: projectUsersTable,
    projects: projectsTable,
    samples: samplesTable,
    trackEffects: trackEffectsTable,
    tracks: tracksTable,
    user: userTable,
  },
  relationships: {
    clips: clipsRelationships,
    projects: projectsRelationships,
    projectUsers: projectUsersRelationships,
    samples: samplesRelationships,
    trackEffects: trackEffectsRelationships,
    tracks: tracksRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "clips" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Clip = Row<(typeof schema)["tables"]["clips"]>;
/**
 * Represents a row from the "projectUsers" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ProjectUser = Row<(typeof schema)["tables"]["projectUsers"]>;
/**
 * Represents a row from the "projects" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Project = Row<(typeof schema)["tables"]["projects"]>;
/**
 * Represents a row from the "samples" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Sample = Row<(typeof schema)["tables"]["samples"]>;
/**
 * Represents a row from the "trackEffects" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TrackEffect = Row<(typeof schema)["tables"]["trackEffects"]>;
/**
 * Represents a row from the "tracks" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Track = Row<(typeof schema)["tables"]["tracks"]>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
