// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { ReadonlyJSONValue, Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const accountTable = {
    "name": "account",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "accountId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "account_id"
        },
        "providerId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "provider_id"
        },
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "accessToken": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "access_token"
        },
        "refreshToken": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "refresh_token"
        },
        "idToken": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "id_token"
        },
        "accessTokenExpiresAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "access_token_expires_at"
        },
        "refreshTokenExpiresAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "refresh_token_expires_at"
        },
        "scope": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "password": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const audioFilesTable = {
    "name": "audioFiles",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "projectId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "project_id"
        },
        "storageUrl": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "storage_url"
        },
        "waveformUrl": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "waveform_url"
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "duration": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number
        },
        "sampleRate": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "sample_rate"
        },
        "channels": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number
        },
        "createdAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "audio_files"
} as const;
const clipsTable = {
    "name": "clips",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "projectId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "project_id"
        },
        "trackId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "track_id"
        },
        "audioFileId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "audio_file_id"
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "startTime": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "start_time"
        },
        "duration": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number
        },
        "audioStartTime": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "audio_start_time"
        },
        "gain": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "createdAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const projectUsersTable = {
    "name": "projectUsers",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "projectId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "project_id"
        },
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        },
        "role": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as "owner" | "collaborator"
        },
        "createdAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "created_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "project_users"
} as const;
const projectsTable = {
    "name": "projects",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "duration": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "sampleRate": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "sample_rate"
        },
        "createdAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const sessionTable = {
    "name": "session",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "expiresAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "expires_at"
        },
        "token": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        },
        "ipAddress": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "ip_address"
        },
        "userAgent": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string,
            "serverName": "user_agent"
        },
        "userId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "user_id"
        }
    },
    "primaryKey": ["id"]
} as const;
const trackEffectsTable = {
    "name": "trackEffects",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "trackId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "track_id"
        },
        "order": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number
        },
        "enabled": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean
        },
        "effectData": {
            "type": "json",
            "optional": false,
            "customType": null as unknown as ReadonlyJSONValue,
            "serverName": "effect_data"
        },
        "createdAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"],
    "serverName": "track_effects"
} as const;
const tracksTable = {
    "name": "tracks",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "projectId": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string,
            "serverName": "project_id"
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "order": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number
        },
        "color": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "muted": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean
        },
        "solo": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean
        },
        "gain": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "pan": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number
        },
        "createdAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const userTable = {
    "name": "user",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "name": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "email": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "emailVerified": {
            "type": "boolean",
            "optional": true,
            "customType": null as unknown as boolean,
            "serverName": "email_verified"
        },
        "image": {
            "type": "string",
            "optional": true,
            "customType": null as unknown as string
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const verificationTable = {
    "name": "verification",
    "columns": {
        "id": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "identifier": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "value": {
            "type": "string",
            "optional": false,
            "customType": null as unknown as string
        },
        "expiresAt": {
            "type": "number",
            "optional": false,
            "customType": null as unknown as number,
            "serverName": "expires_at"
        },
        "createdAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "created_at"
        },
        "updatedAt": {
            "type": "number",
            "optional": true,
            "customType": null as unknown as number,
            "serverName": "updated_at"
        }
    },
    "primaryKey": ["id"]
} as const;
const accountRelationships = {
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
const audioFilesRelationships = {
    "project": [{ "sourceField": ["projectId"], "destField": ["id"], "destSchema": "projects", "cardinality": "one" }],
    "clips": [{ "sourceField": ["id"], "destField": ["audioFileId"], "destSchema": "clips", "cardinality": "many" }]
} as const;
const clipsRelationships = {
    "project": [{ "sourceField": ["projectId"], "destField": ["id"], "destSchema": "projects", "cardinality": "one" }],
    "track": [{ "sourceField": ["trackId"], "destField": ["id"], "destSchema": "tracks", "cardinality": "one" }],
    "audioFile": [{ "sourceField": ["audioFileId"], "destField": ["id"], "destSchema": "audioFiles", "cardinality": "one" }]
} as const;
const projectsRelationships = {
    "users": [{ "sourceField": ["id"], "destField": ["projectId"], "destSchema": "projectUsers", "cardinality": "many" }],
    "tracks": [{ "sourceField": ["id"], "destField": ["projectId"], "destSchema": "tracks", "cardinality": "many" }],
    "audioFiles": [{ "sourceField": ["id"], "destField": ["projectId"], "destSchema": "audioFiles", "cardinality": "many" }],
    "clips": [{ "sourceField": ["id"], "destField": ["projectId"], "destSchema": "clips", "cardinality": "many" }]
} as const;
const projectUsersRelationships = {
    "project": [{ "sourceField": ["projectId"], "destField": ["id"], "destSchema": "projects", "cardinality": "one" }],
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
const sessionRelationships = {
    "user": [{ "sourceField": ["userId"], "destField": ["id"], "destSchema": "user", "cardinality": "one" }]
} as const;
const trackEffectsRelationships = {
    "track": [{ "sourceField": ["trackId"], "destField": ["id"], "destSchema": "tracks", "cardinality": "one" }]
} as const;
const tracksRelationships = {
    "project": [{ "sourceField": ["projectId"], "destField": ["id"], "destSchema": "projects", "cardinality": "one" }],
    "clips": [{ "sourceField": ["id"], "destField": ["trackId"], "destSchema": "clips", "cardinality": "many" }],
    "effects": [{ "sourceField": ["id"], "destField": ["trackId"], "destSchema": "trackEffects", "cardinality": "many" }]
} as const;
const userRelationships = {
    "sessions": [{ "sourceField": ["id"], "destField": ["userId"], "destSchema": "session", "cardinality": "many" }],
    "accounts": [{ "sourceField": ["id"], "destField": ["userId"], "destSchema": "account", "cardinality": "many" }]
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
    "tables": {
        "account": accountTable,
        "audioFiles": audioFilesTable,
        "clips": clipsTable,
        "projectUsers": projectUsersTable,
        "projects": projectsTable,
        "session": sessionTable,
        "trackEffects": trackEffectsTable,
        "tracks": tracksTable,
        "user": userTable,
        "verification": verificationTable
    },
    "relationships": {
        "account": accountRelationships,
        "audioFiles": audioFilesRelationships,
        "clips": clipsRelationships,
        "projects": projectsRelationships,
        "projectUsers": projectUsersRelationships,
        "session": sessionRelationships,
        "trackEffects": trackEffectsRelationships,
        "tracks": tracksRelationships,
        "user": userRelationships
    },
    "enableLegacyQueries": false,
    "enableLegacyMutators": false
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "account" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Account = Row<(typeof schema)["tables"]["account"]>;
/**
 * Represents a row from the "audioFiles" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AudioFile = Row<(typeof schema)["tables"]["audioFiles"]>;
/**
 * Represents a row from the "clips" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Clip = Row<(typeof schema)["tables"]["clips"]>;
/**
 * Represents a row from the "projectUsers" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ProjectUser = Row<(typeof schema)["tables"]["projectUsers"]>;
/**
 * Represents a row from the "projects" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Project = Row<(typeof schema)["tables"]["projects"]>;
/**
 * Represents a row from the "session" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Session = Row<(typeof schema)["tables"]["session"]>;
/**
 * Represents a row from the "trackEffects" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type TrackEffect = Row<(typeof schema)["tables"]["trackEffects"]>;
/**
 * Represents a row from the "tracks" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Track = Row<(typeof schema)["tables"]["tracks"]>;
/**
 * Represents a row from the "user" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type User = Row<(typeof schema)["tables"]["user"]>;
/**
 * Represents a row from the "verification" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Verification = Row<(typeof schema)["tables"]["verification"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module '@rocicorp/zero' { interface DefaultTypes { schema: Schema; } }
